version: '3.8'
services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - db:/var/lib/mysql

  check-db-started: 
    image: jwilder/dockerize:0.6.1
    depends_on:
      - mysqldb
    command: 'dockerize -wait=tcp://mysqldb:3306'

    
  app:
    depends_on:
      - check-db-started
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$APP_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes: 
  db:
